FROM mcr.microsoft.com/playwright:v1.57.0-jammy

WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
RUN npm install --include=dev

COPY . .
RUN npx prisma generate

CMD ["node", "src/monitoring/worker.js"]

